### ISSUE TITLE
TypeError: incompatible marshal file format when use with Rails.

### ISSUE THREAD

**Issue by taiansu** [nateware/redis-objects#147]
I recently update redis-objects from `0.7.0` to `1.0.0`, and got `TypeError: incompatible marshal file format (can't be read) format version 4.8 required; 116.101 given` when I call `Redis::Value.new('key', marshal: true)`.  I tried and got the same error in ruby 2.1.2 and 1.9.3 with Rails 4.1.5 and 3.2.19. Anyone can help? Thanks!

**Comment by outoftime** [comment]
Just had the same problem. Downgrade to 0.8.x fixes it.

**Comment by nateware** [comment]
Thanks guys.  Can you send me examples of the data that gets corrupted?
Then I can try to reproduce.

**Comment by nisanth074** [comment]
Hey @nateware, we faced the exact same issue today in production (and it unfortunately broke a major feature for customers 😢). We had upgraded redis-objects from version 0.5.2 to 0.9.1.

The bug was introduced in version 0.9.0, specifically in this commit https://github.com/nateware/redis-objects/commit/7c41fb6f415ebaf2013b240f224471f3084bb1a0

Here's a way to replicate it
```
~/tmp% gem uninstall redis
...
~/tmp% gem uninstall redis-objects
...
~/tmp% gem install redis -v "3.3.1"
...
~/tmp% gem install redis-objects -v "0.5.2"
...
~/tmp% cat test_redis_objects_crash.rb
require "redis"
require "redis/objects"

Redis::Objects.redis = Redis.new

class Filter
  include Redis::Objects

  attr_accessor :id

  hash_key :rules, :marshal => true
end

filter = Filter.new
filter.id = 1

is_redis_objects_0_9_0 = !(defined? Redis::Helpers::Serialize)

if is_redis_objects_0_9_0
  filter.rules.all
else
  filter.rules[:subject] = "Urgent Emergency"
  filter.rules
end
~/tmp% ruby test_redis_objects_crash.rb
~/tmp% gem install redis-objects -v "0.9.0"
...
~/tmp% ruby test_redis_objects_crash.rb
/Users/nisanth/.rvm/gems/ruby-2.2.3/gems/redis-objects-0.9.0/lib/redis/helpers/core_commands.rb:73:in `load': incompatible marshal file format (can't be read) (TypeError)
	format version 4.8 required; 85.114 given
	from /Users/nisanth/.rvm/gems/ruby-2.2.3/gems/redis-objects-0.9.0/lib/redis/helpers/core_commands.rb:73:in `unmarshal'
	from /Users/nisanth/.rvm/gems/ruby-2.2.3/gems/redis-objects-0.9.0/lib/redis/hash_key.rb:69:in `block in all'
	from /Users/nisanth/.rvm/gems/ruby-2.2.3/gems/redis-objects-0.9.0/lib/redis/hash_key.rb:69:in `each'
	from /Users/nisanth/.rvm/gems/ruby-2.2.3/gems/redis-objects-0.9.0/lib/redis/hash_key.rb:69:in `all'
```

0.5.2 doesn't marshal simple objects like String, Fixnum, Bignum and Float. 0.9.0 (specifically the commit I mentioned above) changed this behaviour and started marshalling all objects. Was this change intentional?
I'm trying to temporarily downgrade to 0.8.0 for now to fix this issue. Do newer versions of redis-objects carry forward the marshalling behaviour from 0.9.0?
