### ISSUE TITLE
Window in which lock may manually be released is too big

### ISSUE THREAD

**Issue by johnc219** [nateware/redis-objects#234]
In the [code below](https://github.com/nateware/redis-objects/blob/master/lib/redis/lock.rb#L69), when the `expiration` is passed as a non-nil option, the key corresponding to the lock is deleted from redis if the `end_time` is greater than the current time.

```ruby
        if @options[:expiration].nil? || end_time > Time.now.to_f
          redis.del(key)
        end
```
We see [here for example](https://github.com/nateware/redis-objects/blob/master/lib/redis/lock.rb#L41) that the end time, upon lock acquisition, is updated to be the current time + the generated expiration. The issue is that the generated expiration is in **milliseconds** rather than seconds, so the `end_time` is set much further into the future than intended.

For example, given an expiration `expiration: 1`, the key will be manually deleted as long as we didn't hold the lock for more than ~1000 seconds (~16.7 minutes).

As a result, we may actually start releasing another owner's lock if that owner acquired it after the key expired in redis from the ttl:

1. client 1 acquires lock and starts doing work
1. lock expires
1. client 2 acquires lock
1. client 1 finishes doing its work, `end_time`, which is further in the future than actual expiration time, is further in the future than the current time, so it releases the lock
1. client 2 is now doing work without holding the lock

---

A solution is to divide the `expiration` by 1000.0 to get it into seconds when adding it to the current time
`end_time = Time.now.to_i + (expiration / 1000.0)`

**Comment by nateware** [comment]
Hey John, thanks for the contribution. While I integrated it because I think you're right that the math was off, I don't think it's possible to fix the lock functionality without a background thread running monitoring locks to reclaim expired ones.  Don't know why that didn't occur to me before. Would be curious if you see your set of commits appreciably changing stuff in production.  There is an edge case where the block exits before expiration which I think is undefined behavior currently.
